package confs

/*
Domains for cloudflare edgetunnel.
*/
var Domains string = `gitlab.com
keywordtool.io
texas.gov
tomshardware.com
tufos.com.br
opencorporates.com
bahn.de
tvn.cl
benzworld.org
blu.com
nationalgeographic.com
ninjakiwi.com
todoexpertos.com
cursorinfo.co.il
contractortalk.com
transparency.org
cityam.com
trawell.in
target.com
klarna.com
checkout.com
online-spellcheck.com
testosterona.blog.br
toppr.com
tudosobrecachorros.com.br
nationalgrid.com
teachstarter.com
canada.ca
cancer.org
textfac.es
nottingham.ac.uk
berliner-zeitung.de
4rsgold.com
tec.mx
concepto.de
bhagavad-gita.org
nzherald.co.nz
battlefieldtracker.com
chase.com
180graus.com
cancerresearchuk.org
kobo.com
overclock.net
thewire.in
back4app.com
trailvoy.com
orfonline.org
tmart.com
theblackpeppercorn.com
tribalfootball.com
tractorpartsasap.com
csu.edu.au
techsupportforum.com
consumidorpositivo.com.br
costco.com
consumerreports.org
bikeradar.com
businessworld.in
besthealthmag.ca
nike.com
kingdomhearts.com
canadavisa.com
n-tv.de
boots.com
24horas.cl
otvfoco.com.br
24smi.info
nitrado.net
oakley.com
chatelaine.com
bloomingdales.com
nadaguides.com
thecarconnection.com
casadecampo.com.do
kicker.de
businesstech.co.za
nairaland.com
thewindowsclub.com
change.org
trezor.io
chordify.net
calendly.com
oecd.org
census2011.co.in
catholicherald.co.uk
cumminsforum.com
knowonlineadvertising.com
talkclassical.com
thenewdaily.com.au
nykaa.com
trueachievements.com
twentytwowords.com
three.co.uk
carfax.com
britannica.com
baseball-reference.com
citizen.co.za
clubmahindra.com
cengage.com
bestbuy.com
crvownersclub.com
campingworld.com
t-shirtforums.com
kknews.cc
bachpan.com
caribbeancinemas.com
omny.fm
billyargel.com
tatamotors.com
tvtonight.com.au
obozrevatel.com
bestdeals.today
thechronicleherald.ca
betapage.co
navionics.com
newgamesbox.net
britishcouncil.org
thisisbarry.com
crosswordquizanswers.com
kickstartyourdrumming.com
tagesspiegel.de
noticiassin.com
openhab.org
cars.com
nuance.com
bollywoodshaadis.com
tandfonline.com
booking.com
conceptodefinicion.de
cryptocompare.com
byjus.com
news-medical.net
cushmanwakefield.com
cars.co.za
thevinylfactory.com
belfasttelegraph.co.uk
theverge.com
bisnis.com
bahai.org
theepochtimes.com
kickstarter.com
cultizm.com
twinstar.cz
creativememories.com
busyteacher.org
oneclass.com
noteburner.com
bluesoft.com.br
online-calculator.com
clipchamp.com
brasil247.com
naturallivingideas.com
chanel.com
build.com.au
4chan.org
oversodoinverso.com.br
kayako.com
nj.com
oficinadanet.com.br
tasteandtellblog.com
10fastfingers.com
cvs.com
brasildefato.com.br
choice.com.au
typing.com
ny.gov
techshout.com
ozbargain.com.au
creativefabrica.com
thestatesman.com
noupe.com
bibliaonline.com.br
nba.com
cookiesandcups.com
onthisday.com
thesourcecad.com
clickastro.com
topix.com
2captcha.com
toyhou.se
nextdoor.com
bannedbook.org
breeders.net
bl.uk
catracalivre.com.br
catholicstraightanswers.com
telefonescelulares.com.br
news24.com
tone2.com
nettv4u.com
nintendolife.com
2ch.hk
knowyourmeme.com
cosmosmagazine.com
topemttraining.com
kanyetothe.com
brainly.in
king.com
tvnotas.com.mx
browserstack.com
tn.com.ar
boticario.com.br
kogan.com
otakukart.com
online-downloader.com
konicaminolta.eu
clubedoaz.com.br
theodysseyonline.com
tattoo-journal.com
commvault.com
centurymedia.com
bestbuy.ca
tedbaker.com
toyotanation.com
ce.gov.br
tribune.com.pk
narcity.com
billboard.com
cpfl.com.br
newcastle.edu.au
thecalculatorsite.com
chip.de
nikon.com
crazygames.com
childdevelopment.com.au
cartier.com
thedieselstop.com
olacabs.com
telegraf.com.ua
officedepot.com.mx
cheapoair.com
trip101.com
100noticias.com.ni
npr.org
todayhumor.co.kr
teclasap.com.br
confused.com
cameradecision.com
tudointeressante.com.br
thecrochetcrowd.com
bandab.com.br
cabelas.com
cargurus.com
covestro.com
ourcodeworld.com
newsner.com
oneeyeland.com
tasteofhome.com
thehindu.com
noise11.com
copaair.com
kinsta.com
todateen.com.br
noblechairs.com
careerone.com.au
cartacapital.com.br
100percentfedup.com
calcuworld.com
timhortons.com
odyclub.com
browneyedbaker.com
teamviewer.com
clinlife.com
tundrasolutions.com
cruisecritic.com
naoconto.com
caribbeanpay.com
tfes.org
theasciicode.com.ar
brickset.com
bfi.org.uk
chicagotribune.com
nokia.com
taxformcalculator.com
beesource.com
nativebase.io
online-stopwatch.com
cochlear.com
teamwork.com
theiconic.com.au
codecanyon.net
belasmensagens.com.br
trulia.com
crossout.net
buzzfeed.com
oyorooms.com
nearmap.com
chomikuj.pl
cricketwireless.com
nikkei.com
coursehero.com
bellybelly.com.au
commbank.com.au
nexusmods.com
cryengine.com
cbs.com
baccredomatic.com
casinomeister.com
cancilleria.gov.co
olx.ua
bitdefender.com
cdmx.gob.mx
breezy.hr
tineye.com
thefinertimes.com
bikerumor.com
newsru.co.il
brfiles.com
tellychakkar.com
brillonline.com
thechive.com
carmax.com
nobelprize.org
nownews.com
nytimes.com
cineworld.co.uk
thomsonreuters.com
ba.gov.br
cinema10.com.br
neonnettle.com
1mg.com
cavsnation.com
ojooo.com
canalrural.com.br
travesticomlocal.com.br
choicehotels.com
theserverside.com
banorte.com
casino.org
oneplus.net
truthfinder.com
kraken.com
complaintsboard.com
techpp.com
canadiantire.ca
typingtest.com
bmj.com
terra.com
timeandtidewatches.com
on.cc
cymatics.fm
tacobell.com
conectate.com.do
cda.pl
tapatalk.com
bayt.com
computerbild.de
tfl.gov.uk
cookieandkate.com
telerik.com
climatempo.com.br
basunivesh.com
bravenewcoin.com
blinkist.com
cliquefarma.com.br
bioexplorer.net
carryology.com
thepennyhoarder.com
ciudad.com.ar
caliente.mx
odditycentral.com
tractorsupply.com
blackboard.com
box.com
kickasstorrents.to
therecipecritic.com
kohls.com
nutriciously.com
tweaktown.com
novritsch.com
beebom.com
outlookindia.com
convenia.com.br
trainzportal.com
tropicalfishkeeping.com
bignox.com
consultaremedios.com.br
neoseeker.com
thepiratebay.org
confessionstories.org
travelmamas.com
concursos.com.br
tripzilla.com
topixoffbeat.com
nitecore.com
clubpremier.com
chegg.com
okchicas.com
chemistwarehouse.com.au
creation.com
oxforddictionaries.com
csgostash.com
biographyonline.net
opentext.com
todaysparent.com
bajaao.com
newegg.com
cybrary.it
checkfront.com
billiger.de
2brightsparks.com
coloringtop.com
careerfaqs.com.au
carsdirect.com
opencolleges.edu.au
ninecolours.com
overstock.com
1millionwomen.com.au
cutekaomoji.com
btgpactual.com
bike24.com
brainly.com
neuber.com
coupons.com
cronica.com.ar
key.com
charlestoncvb.com
tickld.com
beautyheaven.com.au
campos24horas.com.br
blogdoenem.com.br
cifras.com.br
corotos.com.do
thequint.com
caracoltv.com
navi.com
betterteam.com
brainly.com.br
nbcsports.com
chittorgarh.com
officeholidays.com
comidaereceitas.com.br
timetrade.com
opendemocracy.net
careeraddict.com
boards.ie
netmums.com
cronometer.com
oregonlive.com
1000projects.org
citizenfreepress.com
capital.com
baesystems.com
tubecorporate.com
cadillacforums.com
oemdtc.com
bonde.com.br
toyota.com.au
betus.com.pa
bitbond.com
targetstudy.com
kroger.com
bijlibachao.com
cxtv.com.br
the1975.com
thegabrielmethod.com
bigcommerce.com
coingape.com
netflix.com
the-pillow.com.au
ossur.com
onlinetennisinstruction.com
nissan.com.mx
the-digital-reader.com
cloudinary.com
kylieminteriors.ca
themagickalcat.com
thejournal.ie
narvar.com
cna.com
trigtent.com
creditooudebito.com.br
kbb.com
bitso.com
conflictnations.com
taxguru.in
casalsemvergonha.com.br
telstra.com.au
bci.cl
b9.com.br
chevelles.com
codeandweb.com
coolors.co
ovaciondigital.com.uy
ciclovivo.com.br
ome.tv
totvs.com
nareshit.in
badoinkvr.com
tawk.to
thescore.com
kia-forums.com
thewhiskyexchange.com
ngemu.com
time.cloudflare.com
icook.hk
icook.tw
ip.sb
japan.com
malaysia.com
russia.com
singapore.com
www.visa.com
www.visa.com.sg
www.visa.com.hk
www.visa.com.tw
www.visa.co.jp
www.visakorea.com
www.gco.gov.qa
www.gov.ua
www.digitalocean.com
www.csgo.com
www.shopify.com
www.whoer.net
www.whatismyip.com
www.ipget.net
www.hugedornains.com
www.udacity.com
www.4chan.org
www.okcupid.com
www.glassdoor.com
www.udemy.com
www.baipiao.eu.org
`
