package confs

/*
https://github.com/neovim/neovim
https://github.com/sharkdp/fd
https://github.com/BurntSushi/ripgrep
https://github.com/JetBrains/kotlin
https://github.com/gerardog/gsudo
https://github.com/zigtools/zls
https://github.com/typst/typst
https://github.com/nvarner/typst-lsp
https://github.com/vlang/v
https://github.com/v-analyzer/v-analyzer
https://github.com/oven-sh/bun
https://github.com/junegunn/fzf
https://github.com/denoland/deno
*/
var ProjectsFromGithub string = `neovim/neovim
sharkdp/fd
BurntSushi/ripgrep
vlang/v
v-analyzer/v-analyzer
typst/typst
nvarner/typst-lsp
gerardog/gsudo
JetBrains/kotlin
zigtools/zls
oven-sh/bun
junegunn/fzf
denoland/deno
git-for-windows/git
protocolbuffers/protobuf
pmmp/PHP-Binaries
tree-sitter/tree-sitter
charmbracelet/vhs
charmbracelet/glow
gleam-lang/gleam
jesseduffield/lazygit
coursier/coursier`
